---
### defaults for custom variables ###

# ssl
nginx_ssl_dhparam: /etc/nginx/dhparam.pem
nginx_ssl_ciphers: ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384::ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384
nginx_ssl_protocols: TLSv1.1 TLSv1.2

# logs
nginx_access_log_path: /var/log/nginx/access.log
nginx_error_log_path: /var/log/nginx/error.log
