---
common_pkgs:
  - software-properties-common
  - build-essential
  - multiarch-support
  - python-apt
  - dirmngr 
  - apt-transport-https
  - git 
  - curl
  - rsync
  - wget
  - unzip
  - net-tools 
  - resolvconf
  - htop
  - dos2unix
  - autoconf 
  - libgmp-dev
  - cmake
  - zlib1g 
  - zlib1g-dev

libssl_pkgs:
  - libssl1.0.0=1.0.2g-1ubuntu4.15 
  - libssl-dev=1.0.2g-1ubuntu4.15
