---
php_pecl_extensions_install: []

php_extensions_files: 
  - cassandra

php_extensions_enable:
  - cassandra

php_default_version_debian: "7.0"

php_packages:
  - php
  - php-dev
  - php-pear
  - php-common
  - php-cli
  - php-xdebug
  - php-fpm
  - php-gd
  - php-gmp
  - php-xml
  - php-mbstring
  - php-readline
  - php-bcmath
  - php-bz2
  - php-sqlite3
  - php-pdo
  - php-opcache
  - php-json
  - php-imap
  - php-curl
  - php-intl
  - php-zip
  - php-mysql
  - php-pgsql
  - php-pecl-http
  - php-oauth
  - php-apcu-bc