---
- include_vars: libssl_vars.yml
    
- name: APT | download libssl:1.0.0
  get_url:
    url: "{{ libssl_url }}"
    dest: "/tmp"
    checksum: "{{ libssl_checksum }}"
  register: libssl

- name: APT | download libssl-dev:1.0.2g
  get_url:
    url: "{{ libssl_dev_url }}"
    dest: "/tmp"
    checksum: "{{ libssl_dev_checksum }}"
  register: libssl_dev

- name: APT | install libssl:1.0.0
  apt:
    deb: "{{ libssl.dest }}"
    dpkg_options: '--force-downgrade'

- name: APT | install libssl-dev:1.0.2g
  shell: "dpkg -i {{ libssl_dev.dest }}"

- name: APT | install libssl-dev:1.0.2g
  apt:
    deb: "{{ libssl_dev.dest }}"
    dpkg_options: '--force-downgrade'

# - name: install remaining dependencies (libssl:1.0.0)
#   shell: apt-get install -f
