---
# updating libssl is required prior to install cassandra cpp drivers on Debian stretch 
- include_vars: libssl_vars.yml

- name: APT | download newer libssl for debian stretch
  get_url:
    url: "{{ libssl_url }}"
    dest: "/tmp"
  tags: [ 'packages' ]
  
- name: APT | install newer libssl for debian stretch
  apt:
    deb: "/tmp/{{ libssl_pkg }}"
  tags: [ 'packages' ]