---
- name: supervisor | Ensure supervisor is installed
  apt:
    name: supervisor
    state: present

- name: supervisor | Upload main configuration file
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    owner: root
    group: root
  notify: restart supervisor

- name: ansistrano | Deploy rgsupv-dashboard
  include_role:
    name: ansistrano.deploy

- name: filebeat | Install and/or update filebeat configuration
  include_role:
    name: fidanf.filebeat
  tags: ['filebeat']